kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: piviledgedcontainer
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- okd-admin
groups:
- my-admin-group