apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-p-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs/os_cluster_persistant_store/jenkins/data
    server: nfs.openshift.com
  claimRef:
    name: jenkins-pvc-volume
    namespace: deploy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi	